In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")


In [ ]:
f=open ('/content/bank-names.txt','r', errors="ignore")
raw=f.read()
print ("\t\t\tititreading bank-names.txt file")
print (raw)

			ititreading bank-names.txt file
Citation Request:
  This dataset is public available for research. The details are described in [Moro et al., 2011]. 
  Please include this citation if you plan to use this database:

  [Moro et al., 2011] S. Moro, R. Laureano and P. Cortez. Using Data Mining for Bank Direct Marketing: An Application of the CRISP-DM Methodology. 
  In P. Novais et al. (Eds.), Proceedings of the European Simulation and Modelling Conference - ESM'2011, pp. 117-121, Guimarães, Portugal, October, 2011. EUROSIS.

  Available at: [pdf] http://hdl.handle.net/1822/14838
                [bib] http://www3.dsi.uminho.pt/pcortez/bib/2011-esm-1.txt

1. Title: Bank Marketing

2. Sources
   Created by: Paulo Cortez (Univ. Minho) and Sérgio Moro (ISCTE-IUL) @ 2012
   
3. Past Usage:

  The full dataset was described and analyzed in:

  S. Moro, R. Laureano and P. Cortez. Using Data Mining for Bank Direct Marketing: An Application of the CRISP-DM Methodology. 
  In P. Novais et al. (E

In [ ]:
B_full=pd.read_csv("/content/bank-full.csv",index_col=0, sep = ';') 
Bank=pd.read_csv('/content/bank.csv',index_col=0, sep = ';')


In [ ]:
B_full.head()
Bank.head()


job  marital  education default  ...  pdays previous poutcome   y
age                                           ...                             
30    unemployed  married    primary      no  ...     -1        0  unknown  no
33      services  married  secondary      no  ...    339        4  failure  no
35    management   single   tertiary      no  ...    330        1  failure  no
30    management  married   tertiary      no  ...     -1        0  unknown  no
59   blue-collar  married  secondary      no  ...     -1        0  unknown  no

[5 rows x 16 columns]

In [ ]:
Bank.head()

job  marital  education default  ...  pdays previous poutcome   y
age                                           ...                             
30    unemployed  married    primary      no  ...     -1        0  unknown  no
33      services  married  secondary      no  ...    339        4  failure  no
35    management   single   tertiary      no  ...    330        1  failure  no
30    management  married   tertiary      no  ...     -1        0  unknown  no
59   blue-collar  married  secondary      no  ...     -1        0  unknown  no

[5 rows x 16 columns]

In [ ]:
y = pd.get_dummies(Bank['y'], columns = ['y'],prefix = ['y'], drop_first= True)
Bank.head()

job  marital  education default  ...  pdays previous poutcome   y
age                                           ...                             
30    unemployed  married    primary      no  ...     -1        0  unknown  no
33      services  married  secondary      no  ...    339        4  failure  no
35    management   single   tertiary      no  ...    330        1  failure  no
30    management  married   tertiary      no  ...     -1        0  unknown  no
59   blue-collar  married  secondary      no  ...     -1        0  unknown  no

[5 rows x 16 columns]

In [ ]:
#printing with 7 records
y=Bank.iloc[ :7]
print("\t\t\tprinting 7 records") 
print(y)


			printing 7 records
               job  marital  education default  ...  pdays previous poutcome   y
age                                             ...                             
30      unemployed  married    primary      no  ...     -1        0  unknown  no
33        services  married  secondary      no  ...    339        4  failure  no
35      management   single   tertiary      no  ...    330        1  failure  no
30      management  married   tertiary      no  ...     -1        0  unknown  no
59     blue-collar  married  secondary      no  ...     -1        0  unknown  no
35      management   single   tertiary      no  ...    176        3  failure  no
36   self-employed  married   tertiary      no  ...    330        2    other  no

[7 rows x 16 columns]


In [ ]:
print("\t\t\t\t\tprinting top 5 out of 7 records")
y.head()
 

					printing top 5 out of 7 records


job  marital  education default  ...  pdays previous poutcome   y
age                                           ...                             
30    unemployed  married    primary      no  ...     -1        0  unknown  no
33      services  married  secondary      no  ...    339        4  failure  no
35    management   single   tertiary      no  ...    330        1  failure  no
30    management  married   tertiary      no  ...     -1        0  unknown  no
59   blue-collar  married  secondary      no  ...     -1        0  unknown  no

[5 rows x 16 columns]

In [ ]:
print('Jobs: \n', Bank['job'].unique(),'\n')
print('Jobs:\n', Bank['job'].unique(),'\n')
print('education:\n', Bank['education'].unique())

Jobs: 
 ['unemployed' 'services' 'management' 'blue-collar' 'self-employed'
 'technician' 'entrepreneur' 'admin.' 'student' 'housemaid' 'retired'
 'unknown'] 

Jobs:
 ['unemployed' 'services' 'management' 'blue-collar' 'self-employed'
 'technician' 'entrepreneur' 'admin.' 'student' 'housemaid' 'retired'
 'unknown'] 

education:
 ['primary' 'secondary' 'tertiary' 'unknown']


In [ ]:
print("\t\tExploring and demonstrating Python")
import pandas as pd
s = pd.Series([1, 3, 5, 10, 6, 8])
print("Pandas dataseries\n", s)

		Exploring and demonstrating Python
Pandas dataseries
 0     1
1     3
2     5
3    10
4     6
5     8
dtype: int64


In [ ]:
df = pd.DataFrame(np.random.randn(9, 4),columns=['a','b','c','d'])
print("Pandas DataFrame \n", df)


Pandas DataFrame 
           a         b         c         d
0  0.605608 -0.708098 -0.161273  0.593611
1 -0.883625 -1.675791 -1.175730 -0.293397
2 -1.442037  1.091053 -0.883147  0.324965
3  1.901848 -0.443546 -0.473843 -1.115304
4  0.987045 -0.914377 -0.108078  0.014099
5  0.642707  0.206733 -0.105412 -0.888409
6 -0.999710  1.398213  0.406464  0.565612
7 -1.249023  0.129043 -0.284184 -1.395795
8 -0.161168 -1.574298 -0.515015  0.059882


In [ ]:
print("To access a specific element using iloc  \n", df.iloc[0,1])

To access a specific element using iloc  
 -0.7080976669970884


In [ ]:
print("Acessing a specific section of data\n", df.iloc[0:3,0:2])

Acessing a specific section of data
           a         b
0  0.605608 -0.708098
1 -0.883625 -1.675791
2 -1.442037  1.091053


In [ ]:
print("Printing the top section of the dataset \n",df.head(5))

Printing the top section of the dataset 
           a         b         c         d
0  0.605608 -0.708098 -0.161273  0.593611
1 -0.883625 -1.675791 -1.175730 -0.293397
2 -1.442037  1.091053 -0.883147  0.324965
3  1.901848 -0.443546 -0.473843 -1.115304
4  0.987045 -0.914377 -0.108078  0.014099


In [ ]:
print("Printing the bottom section of the dataset \n",df.tail(3))

Printing the bottom section of the dataset 
           a         b         c         d
6 -0.999710  1.398213  0.406464  0.565612
7 -1.249023  0.129043 -0.284184 -1.395795
8 -0.161168 -1.574298 -0.515015  0.059882


In [ ]:
print("Summary of the dataset \n", df.describe())

Summary of the dataset 
               a         b         c         d
count  9.000000  9.000000  9.000000  9.000000
mean  -0.066484 -0.276785 -0.366691 -0.237193
std    1.160660  1.080290  0.465923  0.736786
min   -1.442037 -1.675791 -1.175730 -1.395795
25%   -0.999710 -0.914377 -0.515015 -0.888409
50%   -0.161168 -0.443546 -0.284184  0.014099
75%    0.642707  0.206733 -0.108078  0.324965
max    1.901848  1.398213  0.406464  0.593611


In [ ]:
print(df.to_numpy())

[[ 0.60560793 -0.70809767 -0.16127334  0.59361128]
 [-0.88362482 -1.67579141 -1.17573032 -0.29339704]
 [-1.44203683  1.09105281 -0.88314749  0.32496458]
 [ 1.90184782 -0.44354563 -0.47384279 -1.11530381]
 [ 0.98704462 -0.91437749 -0.10807804  0.01409914]
 [ 0.64270728  0.20673329 -0.10541183 -0.88840857]
 [-0.99971032  1.39821288  0.40646397  0.56561221]
 [-1.24902262  0.12904262 -0.28418393 -1.39579515]
 [-0.16116775 -1.57429788 -0.51501488  0.0598819 ]]
